# Generated by Django 4.0.1 on 2022-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oompa',
            name='name',
        ),
        migrations.AddField(
            model_name='oompa',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
