# Generated by Django 4.0.1 on 2022-01-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_oompa_name_oompa_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='oompa',
            name='salary',
            field=models.IntegerField(default=1),
        ),
    ]
