# Generated by Django 4.0.1 on 2022-01-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
