# Generated by Django 4.0.1 on 2022-01-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_oompa_salary'),
        ('dashboard', '0004_notif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('oompa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.oompa')),
            ],
        ),
    ]
