# Generated by Django 4.0.1 on 2022-01-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='time',
        ),
    ]
