# Generated by Django 4.0.1 on 2022-01-18 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_training_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 7, 15, 37, 383789, tzinfo=utc)),
        ),
    ]
