# Generated by Django 4.0.1 on 2022-01-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_training_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
