# Generated by Django 4.0.1 on 2022-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_training_oompa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chocolates', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
