# Generated by Django 4.0.1 on 2022-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_chocolates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productionperhr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.IntegerField(default=0)),
            ],
        ),
    ]
